---
- name: Determine the OS type
  ansible.builtin.setup:

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: yes

- name: Install required packages for Ubuntu
  ansible.builtin.package:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present
  when: ansible_facts['os_family'] == 'Debian'

- name: Create directory for apt keyrings
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Download Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    owner: root
    group: root

- name: Add Docker repository to APT sources
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Update APT package index again
  ansible.builtin.apt:
    update_cache: yes

- name: Install Docker CE
  ansible.builtin.package:
    name:
      - docker.io
      - docker-compose-v2
    state: present

- name: Ensure Docker service is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: yes
...