---
- name: "[~ Build - Tools Server(s) ~]"
  hosts: all
  become: yes
  roles:
    - docker_ce
    - portainer
    - pihole
    - keycloak
    - node_exporter
    - prometheus_container
    - grafana
  vars:
    prometheus_version: "v3.1.0"
    node_exporter_version: "1.8.2"
...
