kubectl_version: "1.31.4-1.1"
kubeadm_version: "1.31.4-1.1"
kubelet_version: "1.31.4-1.1"
containerd_version: "1.7.12-0ubuntu4.1"

util_packages:
  - ca-certificates
  - curl
  - gpg

k8s_packages:
  - "kubelet={{kubelet_version}}"
  - "kubeadm={{kubeadm_version}}"
  - "kubectl={{kubectl_version}}"

cri_packages:
  - "containerd={{containerd_version}}"

kernel_modules:
  - overlay
  - br_netfilter