---
- name: check current cluster
  shell:
    cmd: curl -k https://localhost:6443/healthz
  register: controlplane_status

- name: initialize kubeadm
  ansible.builtin.shell:
    cmd: sudo kubeadm init --kubernetes-version {{ k8s_run_version }}
  with: controlplane_status.stdout.find("ok") != -1

- name: generate node token
  ansible.builtin.shell:
    cmd: sudo kubeadm token create --print-join-command --ttl {{ node_token_ttl }}
  register: node_join_cmd
...