---
- name: Verify Cluster
  ansible.builtin.uri:
    url: https://localhost:6443/healthz
    validate_certs: false
    return_content: true
  register: controlplane_status
  tags: check-cluster-health
  ignore_errors: true

- ansible.builtin.debug:
    var: controlplane_status
  tags: check-cluster-health

- name: Initialize Bootstrap
  ansible.builtin.shell: sudo kubeadm init --kubernetes-version "{{k8s_run_version}}"
  when: controlplane_status.content != "ok"

- name: Generate Node token
  ansible.builtin.command: kubeadm token create --print-join-command --ttl {{node_token_ttl}}
  register: node_join_cmd

- name: Persist join cmd
  ansible.builtin.add_host:
    name: join_cmd
    cmd: "{{node_join_cmd.stdout}}"
...