---
galaxy_info:
  author: hatluri
  description: Installs and configures Prometheus Node Exporter
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster
  categories:
    - monitoring
dependencies: []
...