---
- name: update all packages
  ansible.builtin.package:
    name: "*"
    state: latest

- name: Adding boot parameters
  lineinfile:
    path: "/boot/cmdline.txt"
    line: "cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1"
    create: yes
...