---
# Stop and remove the AdGuard container
- name: Stop and remove Docker container
  community.docker.docker_container:
    name: adguard
    state: absent
    force_kill: yes

# Remove Docker volume
- name: Remove Docker volume
  community.docker.docker_volume:
    name: "adguard_data"
    state: absent

# Remove AdGuard configuration file
- name: Remove adguardhome.conf
  ansible.builtin.file:
    path: /etc/systemd/resolved.conf.d/adguardhome.conf
    state: absent
...