---
galaxy_info:
  author: hatluri
  description: Deploys Prometheus using Docker.
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - focal
    - name: Debian
      versions:
        - buster
  categories:
    - monitoring
dependencies: []
...